"use client";

import Provider from "@/components/Provider";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import MotionDiv from "@/components/MotionDiv";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <Toaster />
        <body className={inter.className}>
          <MotionDiv>
            <Navbar />
            {children}
            <Footer />
          </MotionDiv>
        </body>
      </Provider>
    </html>
  );
}
