import Provider from "@/components/Provider";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
        <Provider>
          <Toaster />
          <body className={inter.className}>{children}</body>
        </Provider>

    </html>
  );
}
